# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ggregator.proto\x12\naggregator\"J\n\x15\x46\x61\x63\x65\x41ttributesRequest\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x1f\n\x05\x66\x61\x63\x65s\x18\x02 \x03(\x0b\x32\x10.aggregator.Face\"+\n\x04\x46\x61\x63\x65\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x01 \x01(\t\x12\x12\n\nface_image\x18\x02 \x01(\x0c\"\x9c\x01\n\x0b\x45motionInfo\x12\x0f\n\x07\x65motion\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x37\n\x08\x65motions\x18\x03 \x03(\x0b\x32%.aggregator.EmotionInfo.EmotionsEntry\x1a/\n\rEmotionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"!\n\x0cLandmarkInfo\x12\x11\n\tlandmarks\x18\x01 \x03(\x02\"r\n\x08\x46\x61\x63\x65\x44\x61ta\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x01 \x01(\t\x12(\n\x07\x65motion\x18\x02 \x01(\x0b\x32\x17.aggregator.EmotionInfo\x12+\n\tlandmarks\x18\x03 \x01(\x0b\x32\x18.aggregator.LandmarkInfo\"\\\n\x12\x46\x61\x63\x65ResultResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x05\x66\x61\x63\x65s\x18\x03 \x03(\x0b\x32\x14.aggregator.FaceData2g\n\nAggregator\x12Y\n\x12SaveFaceAttributes\x12!.aggregator.FaceAttributesRequest\x1a\x1e.aggregator.FaceResultResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aggregator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMOTIONINFO_EMOTIONSENTRY']._options = None
  _globals['_EMOTIONINFO_EMOTIONSENTRY']._serialized_options = b'8\001'
  _globals['_FACEATTRIBUTESREQUEST']._serialized_start=32
  _globals['_FACEATTRIBUTESREQUEST']._serialized_end=106
  _globals['_FACE']._serialized_start=108
  _globals['_FACE']._serialized_end=151
  _globals['_EMOTIONINFO']._serialized_start=154
  _globals['_EMOTIONINFO']._serialized_end=310
  _globals['_EMOTIONINFO_EMOTIONSENTRY']._serialized_start=263
  _globals['_EMOTIONINFO_EMOTIONSENTRY']._serialized_end=310
  _globals['_LANDMARKINFO']._serialized_start=312
  _globals['_LANDMARKINFO']._serialized_end=345
  _globals['_FACEDATA']._serialized_start=347
  _globals['_FACEDATA']._serialized_end=461
  _globals['_FACERESULTRESPONSE']._serialized_start=463
  _globals['_FACERESULTRESPONSE']._serialized_end=555
  _globals['_AGGREGATOR']._serialized_start=557
  _globals['_AGGREGATOR']._serialized_end=660
# @@protoc_insertion_point(module_scope)
