# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ggregator.proto\x12\x02\x61i\"s\n\nFaceResult\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\x12\x10\n\x08image_id\x18\x03 \x01(\t\x12\x19\n\x11original_filename\x18\x04 \x01(\t\x12\x1b\n\x05\x66\x61\x63\x65s\x18\x05 \x03(\x0b\x32\x0c.ai.FaceData\"\x9b\x01\n\x08\x46\x61\x63\x65\x44\x61ta\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x01 \x01(\t\x12\x12\n\nface_image\x18\x02 \x01(\x0c\x12\x1d\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x0f.ai.BoundingBox\x12$\n\tlandmarks\x18\x04 \x01(\x0b\x32\x11.ai.FaceLandmarks\x12%\n\nage_gender\x18\x05 \x01(\x0b\x32\x11.ai.AgeGenderInfo\"B\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"*\n\rFaceLandmarks\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.ai.Point\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"@\n\rAgeGenderInfo\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\x12\x0e\n\x06gender\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"T\n\x12\x46\x61\x63\x65ResultResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1b\n\x05\x66\x61\x63\x65s\x18\x03 \x03(\x0b\x32\x0c.ai.FaceData2L\n\nAggregator\x12>\n\x12SaveFaceAttributes\x12\x0e.ai.FaceResult\x1a\x16.ai.FaceResultResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aggregator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FACERESULT']._serialized_start=24
  _globals['_FACERESULT']._serialized_end=139
  _globals['_FACEDATA']._serialized_start=142
  _globals['_FACEDATA']._serialized_end=297
  _globals['_BOUNDINGBOX']._serialized_start=299
  _globals['_BOUNDINGBOX']._serialized_end=365
  _globals['_FACELANDMARKS']._serialized_start=367
  _globals['_FACELANDMARKS']._serialized_end=409
  _globals['_POINT']._serialized_start=411
  _globals['_POINT']._serialized_end=440
  _globals['_AGEGENDERINFO']._serialized_start=442
  _globals['_AGEGENDERINFO']._serialized_end=506
  _globals['_FACERESULTRESPONSE']._serialized_start=508
  _globals['_FACERESULTRESPONSE']._serialized_end=592
  _globals['_AGGREGATOR']._serialized_start=594
  _globals['_AGGREGATOR']._serialized_end=670
# @@protoc_insertion_point(module_scope)
