# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/aggregator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/aggregator.proto\x12\naggregator\"{\n\nFaceResult\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\x12\x10\n\x08image_id\x18\x03 \x01(\t\x12\x19\n\x11original_filename\x18\x04 \x01(\t\x12#\n\x05\x66\x61\x63\x65s\x18\x05 \x03(\x0b\x32\x14.aggregator.FaceData\"B\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"\x9c\x01\n\x0b\x45motionInfo\x12\x0f\n\x07\x65motion\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x37\n\x08\x65motions\x18\x03 \x03(\x0b\x32%.aggregator.EmotionInfo.EmotionsEntry\x1a/\n\rEmotionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"!\n\x0cLandmarkInfo\x12\x11\n\tlandmarks\x18\x01 \x03(\x02\"\xad\x01\n\x08\x46\x61\x63\x65\x44\x61ta\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x01 \x01(\t\x12\x12\n\nface_image\x18\x02 \x01(\x0c\x12%\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x17.aggregator.BoundingBox\x12(\n\x07\x65motion\x18\x04 \x01(\x0b\x32\x17.aggregator.EmotionInfo\x12+\n\tlandmarks\x18\x05 \x01(\x0b\x32\x18.aggregator.LandmarkInfo\"\\\n\x12\x46\x61\x63\x65ResultResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x05\x66\x61\x63\x65s\x18\x03 \x03(\x0b\x32\x14.aggregator.FaceData2\\\n\nAggregator\x12N\n\x12SaveFaceAttributes\x12\x16.aggregator.FaceResult\x1a\x1e.aggregator.FaceResultResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.aggregator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMOTIONINFO_EMOTIONSENTRY']._options = None
  _globals['_EMOTIONINFO_EMOTIONSENTRY']._serialized_options = b'8\001'
  _globals['_FACERESULT']._serialized_start=39
  _globals['_FACERESULT']._serialized_end=162
  _globals['_BOUNDINGBOX']._serialized_start=164
  _globals['_BOUNDINGBOX']._serialized_end=230
  _globals['_EMOTIONINFO']._serialized_start=233
  _globals['_EMOTIONINFO']._serialized_end=389
  _globals['_EMOTIONINFO_EMOTIONSENTRY']._serialized_start=342
  _globals['_EMOTIONINFO_EMOTIONSENTRY']._serialized_end=389
  _globals['_LANDMARKINFO']._serialized_start=391
  _globals['_LANDMARKINFO']._serialized_end=424
  _globals['_FACEDATA']._serialized_start=427
  _globals['_FACEDATA']._serialized_end=600
  _globals['_FACERESULTRESPONSE']._serialized_start=602
  _globals['_FACERESULTRESPONSE']._serialized_end=694
  _globals['_AGGREGATOR']._serialized_start=696
  _globals['_AGGREGATOR']._serialized_end=788
# @@protoc_insertion_point(module_scope)
